"""Word (.docx) version of the case report.

Mirrors the PDF export: title, case metadata, then the sections the officer selected. Every AI-derived
pattern carries a visible "AI-derived lead — verify before use" line, and the document ends with an
audit footer saying who exported it, when, and why.
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

AI_LEAD_NOTICE = "AI-derived lead — verify before use"
_RED = RGBColor(0xB4, 0x23, 0x18)
_GREY = RGBColor(0x55, 0x55, 0x55)


def _notice(container, text: str = AI_LEAD_NOTICE) -> None:
    run = container.add_paragraph().add_run(text)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = _RED


def build_case_docx(
    case: dict,
    sections: list[str],
    patterns: list[dict],
    exported_by: str,
    exported_at: datetime,
    justification: Optional[str],
) -> bytes:
    doc = Document()

    # Running header so the caveat survives on every page.
    header = doc.sections[0].header.paragraphs[0]
    header.text = f"ARGUS — {AI_LEAD_NOTICE}"
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in header.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = _RED

    doc.add_heading(case["title"], level=0)

    meta = doc.add_table(rows=0, cols=2)
    meta.style = "Light Grid Accent 1"
    for label, value in [
        ("Case ID", case["case_id"]),
        ("FIR number", case["fir_number"]),
        ("Jurisdiction", case["jurisdiction"]),
        ("Status", case["status"]),
        ("Category", case.get("category") or "—"),
        ("Sensitive", f"Yes — {case.get('sensitivity_reason') or 'reason not recorded'}" if case["is_sensitive"] else "No"),
        ("Opened", case["opened_at"]),
    ]:
        row = meta.add_row().cells
        row[0].text, row[1].text = label, str(value)

    if "Entity List" in sections:
        doc.add_heading("Entity List", level=1)
        if case["entities"]:
            table = doc.add_table(rows=1, cols=3)
            table.style = "Light Grid Accent 1"
            for cell, text in zip(table.rows[0].cells, ("Entity", "Type", "Pinned by")):
                cell.text = text
            for e in case["entities"]:
                cells = table.add_row().cells
                cells[0].text, cells[1].text, cells[2].text = e["entity_value"], e["entity_type"], e["linked_by"]
        else:
            doc.add_paragraph("No entities pinned.")

    if "Notes" in sections:
        doc.add_heading("Notes", level=1)
        if case["notes"]:
            for n in case["notes"]:
                doc.add_paragraph(f"{n['content']} — {n['author']}", style="List Bullet")
        else:
            doc.add_paragraph("No notes.")

    if "Pattern Findings" in sections:
        doc.add_heading("Pattern Findings", level=1)
        if patterns:
            for p in patterns:
                para = doc.add_paragraph(style="List Bullet")
                para.add_run(p["description"]).bold = True
                para.add_run(f"  ({round(p['confidence'] * 100)}% confidence)")
                if p.get("women_safety_flag"):
                    flag = para.add_run("  [Women Safety]")
                    flag.bold = True
                    flag.font.color.rgb = _RED
                if p.get("explanation"):
                    detail = doc.add_paragraph(p["explanation"])
                    detail.paragraph_format.left_indent = Pt(18)
                    for run in detail.runs:
                        run.font.size = Pt(9)
                        run.font.color.rgb = _GREY
                _notice(doc)
        else:
            doc.add_paragraph("No detected patterns involve this case's pinned entities.")

    if "Source Citations" in sections:
        doc.add_heading("Source Citations", level=1)
        if case["entities"]:
            for e in case["entities"]:
                doc.add_paragraph(f"{case['fir_number']}: {e['entity_value']}", style="List Bullet")
        else:
            doc.add_paragraph("No citations.")

    doc.add_paragraph()
    footer = doc.add_paragraph()
    run = footer.add_run(
        f"Exported by {exported_by} at {exported_at.strftime('%Y-%m-%d %H:%M:%S %Z').strip()}, "
        f"justification: {justification or 'none given'}"
    )
    run.italic = True
    run.font.size = Pt(9)
    disclaimer = doc.add_paragraph(
        "Generated by ARGUS. AI-derived content is an investigative lead and must be corroborated "
        "before evidentiary use. This export is recorded in the audit trail."
    )
    for r in disclaimer.runs:
        r.font.size = Pt(8)
        r.font.color.rgb = _GREY

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
